version: '3.8'

services:
  stremioarrs:
    build: .
    container_name: stremioarrs
    init: true
    restart: unless-stopped
    ports:
      - "5100:5100"
    environment:
      - OMDB_API_KEY=${OMDB_API_KEY:-}
